name: 'Build EDB'
description: 'Build the EDB debugger from source'
inputs:
  os:
    required: true
  target:
    required: true
  otp-version:
    required: true

runs:
  using: composite
  steps:
  - name: Checkout EDB
    uses: "actions/checkout@v4"
    with:
      repository: WhatsApp/edb
      path: edb
      ref: otp-28.0
  - name: Build EDB (No Windows)
    if: inputs.os != 'windows'
    run: rebar3 escriptize
    shell: bash
    working-directory: edb
  - name: Build EDB (Windows Only)
    if: inputs.os == 'windows'
    run: rebar3.cmd escriptize
    shell: bash
    working-directory: edb
  - name: Upload EDB binary (No Windows)
    if: inputs.os != 'windows'
    uses: "actions/upload-artifact@v4"
    with:
      name: edb-${{ inputs.os }}-${{ inputs.target }}-otp-${{ inputs.otp-version }}
      path: _build/default/bin/edb
  - name: Upload EDB binary (Windows Only)
    if: inputs.os == 'windows'
    uses: "actions/upload-artifact@v4"
    with:
      name: edb-${{ inputs.os }}-${{ inputs.target }}-otp-${{ inputs.otp-version }}
      path: _build\default\bin\edb
