name: 'Build EDB'
description: 'Build the EDB debugger from source'
runs:
  using: "composite"
  steps:
    - name: Checkout EDB
      uses: "actions/checkout@v4"
      with:
        repository: WhatsApp/edb
        path: edb
        ref: otp-28.0
    - name: Build EDB (No Windows)
        if: matrix.os != 'windows'
        run: rebar3 escriptize
    - name: Build EDB (Windows Only)
        if: matrix.os == 'windows'
        run: rebar3.cmd escriptize
