%%%-------------------------------------------------------------------
%%% @doc
%%% Auto-generated type definitions for example_service
%%% DO NOT EDIT - Generated by generate_erlang.sh
%%% @end
%%%-------------------------------------------------------------------
-module(example_service_types).

%% API exports
-export([new_user_info/0]).
-export([new_query_request/0]).
-export([new_query_response/0]).
-export([get_version/0]).

%% Type exports
-export_type([user_info/0]).
-export_type([query_request/0]).
-export_type([query_response/0]).

%% Record definitions
-record(user_info, {user_id = <<>>, username = <<>>, age = 0, is_active = false}).
-record(query_request, {query_id = <<>>, filters = []}).
-record(query_response, {results = [], count = 0}).

%% Type definitions
-type user_info() :: #user_info{}.
-type query_request() :: #query_request{}.
-type query_response() :: #query_response{}.

%%%===================================================================
%%% API
%%%===================================================================

%% @doc Returns the schema version
-spec get_version() -> binary().
get_version() ->
    <<"1.0.0">>.


%% @doc Creates a new user_info record
-spec new_user_info() -> #user_info{}.
new_user_info() ->
    #user_info{}.


%% @doc Creates a new query_request record
-spec new_query_request() -> #query_request{}.
new_query_request() ->
    #query_request{}.


%% @doc Creates a new query_response record
-spec new_query_response() -> #query_response{}.
new_query_response() ->
    #query_response{}.

