oncall("vscode_erlang")

erlang_application(
    name = "app_a",
    srcs = glob(["app_a/src/*.erl"]),
    applications = [
        ":app_b",
    ],
    labels = ["user_application"],
    version = "1.0.0",
)

erlang_application(
    name = "app_b",
    srcs = glob(["app_b/src/*.erl"]),
    labels = ["user_application"],
    version = "1.0.0",
)

erlang_application(
    name = "app_c",
    srcs = glob(["app_c/src/*.erl"]),
    labels = ["user_application"],
    version = "1.0.0",
)
