oncall("vscode_erlang")

erlang_application(
    name = "assist_examples",
    srcs = glob([
        "src/*.erl",
    ]),
    app_src = "src/assist_examples.app.src",
    applications = [],
    includes = [],
    labels = ["user_application"],
    version = "1.0.0",
    visibility = ["PUBLIC"],
)
