oncall("vscode_erlang")

erlang_application(
    name = "diagnostics_app_a_target",
    srcs = glob(["app_a/src/*.erl"]),
    app_name = "diagnostics_app_a",
    app_src = "app_a/src/app_a.app.src",
    applications = [
    ],
    includes = glob(["app_a/include/*.hrl"]),
    labels = ["user_application"],
    version = "1.0.0",
)

erlang_tests(
    suites = [
        "app_a/test/app_a_SUITE.erl",
    ],
    deps = [":diagnostics_app_a_target"],
)
