name: 'eqwalizer'
description: 'Build the eqWAlizer type checker froum source'
runs:
  using: composite
  steps:
  - name: Checkout eqwalizer
    uses: "actions/checkout@v3"
    with:
      repository: WhatsApp/eqwalizer
      path: eqwalizer
      ref: main
  - name: Set up GraalVM
    uses: graalvm/setup-graalvm@v1
    with:
      java-version: '17'
      distribution: 'graalvm'
      github-token: ${{ secrets.GITHUB_TOKEN }}
  - name: Set up SBT
    uses: olafurpg/setup-scala@v14
    with:
      java-version: '17'
  - name: Assemble eqwalizer.jar (No Windows)
    if: matrix.os != 'windows'
    working-directory: eqwalizer/eqwalizer
    run: "sbt assembly"
  - name: Assemble eqwalizer.jar (Windows Only)
    if: matrix.os == 'windows'
    working-directory: eqwalizer\eqwalizer
    run: "sbt assembly"
    shell: bash
  - name: Assemble eqwalizer binary (No Windows)
    if: matrix.os != 'windows'
    working-directory: eqwalizer/eqwalizer
    run: 'native-image -H:IncludeResources=application.conf --no-server --no-fallback -jar target/scala-3.6.4/eqwalizer.jar eqwalizer'
  - name: Assemble eqwalizer binary (Windows Only)
    if: matrix.os == 'windows'
    working-directory: eqwalizer\eqwalizer
    run: 'native-image -H:IncludeResources=application.conf --no-server --no-fallback -jar target\scala-3.6.4\eqwalizer.jar eqwalizer'
  - name: Configure Environment (No Windows)
    if: matrix.os != 'windows'
    run: |
      echo "EQWALIZER_DIR=${{ github.workspace }}/eqwalizer/eqwalizer" >> $GITHUB_ENV
      echo "ELP_EQWALIZER_PATH=${{ github.workspace }}/eqwalizer/eqwalizer/eqwalizer" >> $GITHUB_ENV
  - name: Configure Environment (Windows Only)
    if: matrix.os == 'windows'
    run: |
      echo "EQWALIZER_DIR=${{ github.workspace }}\eqwalizer\eqwalizer" >> $env:GITHUB_ENV
      echo "ELP_EQWALIZER_PATH=${{ github.workspace }}\eqwalizer\eqwalizer\eqwalizer.exe" >> $env:GITHUB_ENV
