on:
  workflow_call:

jobs:
  eqwalizer-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout eqwalizer
        uses: actions/checkout@v4
        with:
          repository: WhatsApp/eqwalizer

      - name: Assemble eqwalizer.jar
        working-directory: eqwalizer
        run: |
          sbt assembly

      # - name: Test eqwalizer
      #   working-directory: eqwalizer
      #   run: |
      #     sbt test

      - name: "Upload artifact: eqwalizer.jar"
        uses: actions/upload-artifact@v4
        with:
          name: eqwalizer.jar
          path: ./eqwalizer/target/scala-2.13/eqwalizer.jar