on:
  workflow_call:
env:
  EQWALIZER_DIR: ${{ github.workspace }}/eqwalizer/eqwalizer
  ELP_EQWALIZER_PATH: ${{ github.workspace }}/eqwalizer/eqwalizer/eqwalizer

jobs:
  elp:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-apple-darwin
          - aarch64-apple-darwin
        otp-version: [25.3, 26.0]
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu
            os-version: 20.04
            arch: x86_64
          - target: aarch64-unknown-linux-gnu
            os: ubuntu
            os-version: 20.04
            arch: aarch64
          - target: x86_64-apple-darwin
            os: macos
            os-version: latest
            arch: x86_64
          - target: aarch64-apple-darwin
            os: macos
            os-version: latest
            arch: aarch64
    runs-on: ${{ matrix.os }}-${{ matrix.os-version }}
    steps:
      - name: Checkout erlang-language-platform
        uses: actions/checkout@v4
      - name: Checkout eqwalizer
        uses: actions/checkout@v4
        with:
          repository: WhatsApp/eqwalizer
          path: eqwalizer
      - name: "Download artifact: eqwalizer.${{ matrix.target }}"
        uses: actions/download-artifact@v4
        with:
          name: eqwalizer.${{ matrix.target }}
          path: ${{ env.ELP_EQWALIZER_PATH }}
      - name: Set up cross-compiler
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y crossbuild-essential-arm64
      - name: Set up rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}
      - name: Install Erlang/OTP (Linux Only)
        if: matrix.os == 'linux'
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp-version }}
          install-rebar: false
          install-hex: false
      - name: Install Erlang/OTP (MacOS Only)
        if: matrix.os == 'macos'
        run: |
          brew install erlang@${{ matrix.otp-version }}
          echo '/usr/local/opt/erlang@${{ matrix.brew-otp-version }}/bin' >> $GITHUB_PATH
      - name: Verify Erlang/OTP version
        run: |
          erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().' -noshell
      - name: Install rebar3
        run: |
          mkdir rebar3
          curl https://s3.amazonaws.com/rebar3/rebar3 -o rebar3/rebar3
          chmod +x rebar3/rebar3
          echo "$GITHUB_WORKSPACE/rebar3" >> $GITHUB_PATH
      - name: Verify rebar3 version
        run: rebar3 version
      - name: Build elp
        run: |
          cargo build \
            --release  \
            --target ${{ matrix.target }} \
            --config target.aarch64-unknown-linux-gnu.linker=\"aarch64-linux-gnu-gcc\"
      - name: "Upload artifact: elp.otp-${{ matrix.otp-version }}.${{ matrix.target }}"
        uses: "actions/upload-artifact@v4"
        with:
          name: elp.otp-${{ matrix.otp-version }}.${{ matrix.target }}
          path: target/${{ matrix.target }}/release/elp