on:
  workflow_call:

jobs:
  eqwalizer-jar:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout eqwalizer
        uses: actions/checkout@v4
        with:
          repository: WhatsApp/eqwalizer
      - name: Assemble eqwalizer.jar
        working-directory: eqwalizer
        run: |
          sbt assembly
      # - name: Test eqwalizer
      #   working-directory: eqwalizer
      #   run: |
      #     sbt test
      - name: "Upload artifact: eqwalizer.jar"
        uses: actions/upload-artifact@v4
        with:
          name: eqwalizer.jar
          path: ./eqwalizer/target/scala-2.13/eqwalizer.jar

  eqwalizer-native-linux-aarch64:
    needs: eqwalizer-jar
    runs-on: ubuntu-20.04
    steps:
      - name: "Download artifact: eqwalizer.jar"
        uses: actions/download-artifact@v4
        with:
          name: eqwalizer.jar
          path: artifacts/
      - name: Assemble eqwalizer binary
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          setup: |
            GRAALVM_URL=https://download.oracle.com/graalvm/17/latest/graalvm-jdk-17_linux-aarch64_bin.tar.gz
            GRAALVM_SHA256=$(curl -s "${GRAALVM_URL}.sha256")
            curl --output graalvm.tar.gz "${GRAALVM_URL}"
            echo "$GRAALVM_SHA256  graalvm.tar.gz" | shasum -a 256 -c
            mkdir graalvm
            tar -xzf graalvm.tar.gz -C graalvm --strip-components=1
          dockerRunArgs: |
            --volume "${PWD}/graalvm:/graalvm"
            --volume "${PWD}/artifacts:/artifacts"
          run: |
            apt-get -q update
            apt-get -q install -y zlib1g-dev build-essential
            /graalvm/bin/native-image \
              -H:IncludeResources=application.conf \
              --no-server \
              --no-fallback \
              -jar /artifacts/eqwalizer.jar \
              /artifacts/eqwalizer
      - name: "Upload artifact: eqwalizer.aarch64-unknown-linux-gnu"
        uses: actions/upload-artifact@v4
        with:
          name: eqwalizer.aarch64-unknown-linux-gnu
          path: ./eqwalizer/eqwalizer/eqwalizer

  eqwalizer-native:
    needs: eqwalizer-jar
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          # - aarch64-unknown-linux-gnu
          - x86_64-apple-darwin
          - aarch64-apple-darwin
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu
            os-version: 20.04
            arch: x86_64
          # - target: aarch64-unknown-linux-gnu
          #   os: ubuntu
          #   os-version: 20.04
          #   arch: aarch64
          - target: x86_64-apple-darwin
            os: macos
            os-version: latest
            arch: x86_64
          - target: aarch64-apple-darwin
            os: macos
            os-version: latest
            arch: aarch64
    runs-on: ${{ matrix.os }}-${{ matrix.os-version }}
    steps:
      - name: "Download artifact: equalizer.jar"
        uses: actions/download-artifact@v4
        with:
          name: eqwalizer.jar
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ github.token }}
      - name: Assemble eqwalizer binary
        run: |
          native-image \
            -H:IncludeResources=application.conf \
            --no-server \
            --no-fallback \
            -jar eqwalizer.jar \
            eqwalizer.${{ matrix.target }}
      - name: "Upload artifact: eqwalizer.${{ matrix.target }}"
        uses: actions/upload-artifact@v4
        with:
          name: eqwalizer.${{ matrix.target }}
          path: ./eqwalizer/eqwalizer.${{ matrix.target }}