on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      otp-version:
        required: true
        type: string

jobs:
  vscode-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout erlang-language-platform
        uses: actions/checkout@v4

      - name: Prepare VS Code Extension to host binaries
        run: |
          mkdir -p editors/code/bin

      - name: "Download artifact: eqwalizer.${{ inputs.target }}"
        uses: actions/download-artifact@v4
        with:
          name: eqwalizer.${{ inputs.target }}

      - name: "Download artifact: elp.otp-${{ inputs.otp-version }}.${{ inputs.target }}"
        uses: actions/download-artifact@v4
        with:
          name: elp.otp-${{ inputs.otp-version }}.${{ inputs.target }}

      - name: Move elp/eqwalizer binaries
        run: |
          mkdir -p editors/code/bin/
          ls -lh
          mv eqwalizer.${{ inputs.target }} editors/code/bin/eqwalizer
          mv elp.otp-${{ inputs.otp-version }}.${{ inputs.target }} editors/code/bin/elp
          chmod +x editors/code/bin/*

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install VSCE
        run: |
          npm install -g @vscode/vsce

      - name: Build extension
        working-directory: editors/code
        run: |
          echo "::group::Determining vscode target"
          echo "target = ${{ inputs.target }}"
          case "${{ inputs.target }}" in
            x86_64-unknown-linux-gnu) vscode_target=linux-x64 ;;
            aarch64-unknown-linux-gnu) vscode_target=linux-arm64 ;;
            x86_64-apple-darwin) vscode_target=darwin-x64 ;;
            aarch64-apple-darwin) vscode_target=darwin-arm64 ;;
            *)
              echo "Unsupported target platform" >&2
              exit 1
          esac
          echo "vscode-target = ${vscode_target}"
          echo "::endgroup::"

          echo "::group::Build extension"
          npm install
          npm run compile
          vsce package \
            --target "${vscode_target}" \
            --out "elp.otp-${{ inputs.otp-version }}.${{ inputs.target }}.vsix"
          echo "::endgroup::"
      - name: "Upload artifact: elp.otp-${{ inputs.otp-version }}.${{ inputs.target }}.vsix"
        uses: actions/upload-artifact@v4
        with:
          name: elp.otp-${{ inputs.otp-version }}.${{ inputs.target }}.vsix
          path: editors/code/elp.otp-${{ inputs.otp-version }}.${{ inputs.target }}.vsix